import { createServerClient } from '@/lib/supabase/server';
import Link from 'next/link';
import { Sparkles, Calendar, ArrowRight } from 'lucide-react';

export const metadata = {
    title: 'Market Insights & AI Trends | ArtIntel Blog',
    description: 'Stay ahead of the art market with our AI-driven reports, demand heatmaps, and seller strategies.',
};

export default async function BlogIndex() {
    const supabase = await createServerClient();

    const { data: posts, error } = await supabase
        .from('blog_posts')
        .select('*')
        .eq('is_published', true)
        .order('published_at', { ascending: false });

    return (
        <div className="min-h-screen bg-[#050505] text-white pt-32 pb-20 px-6">
            <div className="max-w-7xl mx-auto">
                <div className="mb-16 text-center">
                    <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-xs font-black uppercase tracking-widest mb-6">
                        <Sparkles className="h-3.5 w-3.5" />
                        Market Intelligence
                    </div>
                    <h1 className="text-5xl md:text-7xl font-black mb-6 tracking-tighter">
                        Art Market <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-purple-600">Pulse</span>
                    </h1>
                    <p className="text-gray-400 text-lg max-w-2xl mx-auto">
                        Data-backed insights generated by our AI intelligence engine to help you navigate the 2025 art landscape.
                    </p>
                </div>

                {(!posts || posts.length === 0) ? (
                    <div className="flex flex-col items-center justify-center py-20 border border-dashed border-gray-800 rounded-3xl">
                        <p className="text-gray-500 font-bold">Our AI is currently drafting fresh market reports...</p>
                        <p className="text-gray-700 text-xs mt-2 italic">Check back in a few minutes.</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {posts.map((post) => (
                            <Link
                                key={post.id}
                                href={`/blog/${post.slug}`}
                                className="group relative flex flex-col bg-gray-900/40 border border-gray-800 rounded-3xl overflow-hidden transition-all hover:border-blue-500/50 hover:bg-gray-900/60"
                            >
                                <div className="aspect-[16/9] w-full bg-gray-800 relative overflow-hidden">
                                    {post.featured_image_url ? (
                                        <img
                                            src={post.featured_image_url}
                                            alt={post.title}
                                            className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                                        />
                                    ) : (
                                        <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-gray-800 to-gray-900">
                                            <Sparkles className="h-12 w-12 text-gray-700 opacity-50" />
                                        </div>
                                    )}
                                </div>

                                <div className="p-8 flex-1 flex flex-col">
                                    <div className="flex items-center gap-4 text-[10px] text-gray-500 font-black uppercase tracking-widest mb-4">
                                        <span className="flex items-center gap-1">
                                            <Calendar className="h-3 w-3" />
                                            {new Date(post.published_at).toLocaleDateString()}
                                        </span>
                                        <span className="h-1 w-1 rounded-full bg-gray-700" />
                                        <span>{post.author_name}</span>
                                    </div>

                                    <h2 className="text-2xl font-black mb-4 leading-tight group-hover:text-blue-400 transition-colors">
                                        {post.title}
                                    </h2>

                                    <p className="text-gray-400 text-sm line-clamp-3 mb-8 flex-1 leading-relaxed">
                                        {post.meta_description}
                                    </p>

                                    <div className="flex items-center gap-2 text-blue-500 text-xs font-black uppercase tracking-widest group-hover:gap-4 transition-all">
                                        Read Analysis
                                        <ArrowRight className="h-4 w-4" />
                                    </div>
                                </div>
                            </Link>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}
