'use client';

import { useState } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { Download, Sparkles, Heart, Star, Gift, Check } from 'lucide-react';
import { GeminiAIService } from '@/services/ai/gemini-service';
import { jsPDF } from 'jspdf';

interface ThankYouCard {
    id: string;
    title: string;
    template: 'classic' | 'modern' | 'minimal' | 'artistic';
    message: string;
    signature: string;
}

export default function ThankYouCardGenerator() {
    const [loading, setLoading] = useState(false);
    const [formData, setFormData] = useState({
        buyerName: '',
        artworkTitle: '',
        artistName: '',
        personalNote: '',
        template: 'modern' as const
    });
    const [generatedCard, setGeneratedCard] = useState<ThankYouCard | null>(null);

    const templates = [
        {
            id: 'classic',
            name: 'Classic Elegance',
            icon: Heart,
            description: 'Timeless and professional',
            color: 'from-amber-600 to-amber-700'
        },
        {
            id: 'modern',
            name: 'Modern Vibrant',
            icon: Sparkles,
            description: 'Bold and contemporary',
            color: 'from-blue-600 to-purple-600'
        },
        {
            id: 'minimal',
            name: 'Minimal Chic',
            icon: Star,
            description: 'Clean and sophisticated',
            color: 'from-gray-600 to-gray-700'
        },
        {
            id: 'artistic',
            name: 'Artistic Flair',
            icon: Gift,
            description: 'Creative and unique',
            color: 'from-pink-600 to-rose-700'
        }
    ];

    const handleGenerate = async () => {
        if (!formData.buyerName || !formData.artworkTitle || !formData.artistName) {
            alert('Please fill in all required fields');
            return;
        }

        setLoading(true);

        try {
            // Generate AI-powered thank you message
            const aiMessage = await GeminiAIService.generateThankYouMessage(
                formData.buyerName,
                formData.artworkTitle,
                formData.artistName,
                formData.personalNote
            );

            const card: ThankYouCard = {
                id: `card-${Date.now()}`,
                title: `Thank You, ${formData.buyerName}!`,
                template: formData.template,
                message: aiMessage,
                signature: formData.artistName
            };

            setGeneratedCard(card);
        } catch (error) {
            console.error('Error generating card:', error);
            alert('Failed to generate card. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    const handleDownload = () => {
        if (!generatedCard) return;

        const doc = new jsPDF({
            orientation: 'landscape',
            unit: 'in',
            format: [7, 5]
        });

        // Background Color based on template
        const colors = {
            classic: { bg: [255, 251, 235], accent: [180, 83, 9] },
            modern: { bg: [245, 247, 255], accent: [37, 99, 235] },
            minimal: { bg: [255, 255, 255], accent: [75, 85, 99] },
            artistic: { bg: [255, 241, 242], accent: [225, 29, 72] }
        };

        const theme = colors[generatedCard.template as keyof typeof colors] || colors.modern;

        // Fill background
        doc.setFillColor(theme.bg[0], theme.bg[1], theme.bg[2]);
        doc.rect(0, 0, 7, 5, 'F');

        // Decorative Border
        doc.setDrawColor(theme.accent[0], theme.accent[1], theme.accent[2]);
        doc.setLineWidth(0.05);
        doc.rect(0.25, 0.25, 6.5, 4.5);

        // Title
        doc.setTextColor(51, 51, 51);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(32);
        doc.text(generatedCard.title, 3.5, 1.2, { align: 'center' });

        // Message
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(14);
        doc.setTextColor(85, 85, 85);
        const splitMessage = doc.splitTextToSize(generatedCard.message, 5.5);
        doc.text(splitMessage, 3.5, 2.0, { align: 'center' });

        // Signature
        doc.setFont('helvetica', 'bolditalic');
        doc.setFontSize(20);
        doc.setTextColor(theme.accent[0], theme.accent[1], theme.accent[2]);
        doc.text(`— ${generatedCard.signature}`, 3.5, 4.0, { align: 'center' });

        // Footer
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(156, 163, 175);
        doc.text('Generated by ArtScaler', 3.5, 4.7, { align: 'center' });

        doc.save(`thank-you-${formData.buyerName.replace(/\s+/g, '-').toLowerCase()}.pdf`);
    };

    return (
        <DashboardLayout>
            <div className="max-w-6xl mx-auto space-y-8">
                {/* Header */}
                <div className="text-left">
                    <h1 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
                        <Heart className="h-8 w-8 text-pink-500" />
                        Thank You Card Generator
                    </h1>
                    <p className="text-gray-400">
                        Create beautiful, AI-powered thank you cards for your collectors
                    </p>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Form */}
                    <div className="bg-gray-900 border border-gray-800 rounded-3xl p-8">
                        <h2 className="text-xl font-bold text-white mb-6">Order Details</h2>

                        <div className="space-y-6">
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">
                                        Buyer Name
                                    </label>
                                    <input
                                        type="text"
                                        value={formData.buyerName}
                                        onChange={(e) => setFormData({ ...formData, buyerName: e.target.value })}
                                        className="w-full px-4 py-3 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-blue-500 font-bold"
                                        placeholder="John Smith"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">
                                        Artwork Title
                                    </label>
                                    <input
                                        type="text"
                                        value={formData.artworkTitle}
                                        onChange={(e) => setFormData({ ...formData, artworkTitle: e.target.value })}
                                        className="w-full px-4 py-3 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-blue-500 font-bold"
                                        placeholder="Sunset Dreams"
                                    />
                                </div>
                            </div>

                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">
                                    Your Artist Name
                                </label>
                                <input
                                    type="text"
                                    value={formData.artistName}
                                    onChange={(e) => setFormData({ ...formData, artistName: e.target.value })}
                                    className="w-full px-4 py-3 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-blue-500 font-bold"
                                    placeholder="Jane Artist"
                                />
                            </div>

                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">
                                    Personal Impression (Optional)
                                </label>
                                <textarea
                                    value={formData.personalNote}
                                    onChange={(e) => setFormData({ ...formData, personalNote: e.target.value })}
                                    className="w-full px-4 py-3 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-blue-500 h-24 resize-none"
                                    placeholder="Add a personal touch..."
                                />
                            </div>

                            {/* Template Selection */}
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-4">
                                    Visual Theme
                                </label>
                                <div className="grid grid-cols-2 gap-3">
                                    {templates.map((template) => {
                                        const Icon = template.icon;
                                        return (
                                            <button
                                                key={template.id}
                                                onClick={() => setFormData({ ...formData, template: template.id as any })}
                                                className={`p-4 rounded-xl border-2 transition-all text-left ${formData.template === template.id
                                                    ? 'border-blue-500 bg-blue-900/20'
                                                    : 'border-gray-800 hover:border-gray-700'
                                                    }`}
                                            >
                                                <div className={`w-8 h-8 bg-gradient-to-br ${template.color} rounded-lg flex items-center justify-center mb-2`}>
                                                    <Icon className="h-4 w-4 text-white" />
                                                </div>
                                                <div className="text-white font-bold text-xs">{template.name}</div>
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            <button
                                onClick={handleGenerate}
                                disabled={loading}
                                className="w-full py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-black rounded-xl hover:shadow-2xl hover:shadow-blue-500/30 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
                            >
                                {loading ? 'Drafting Message...' : 'Generate Card ✨'}
                            </button>
                        </div>
                    </div>

                    {/* Preview */}
                    <div className="bg-gray-900 border border-gray-800 rounded-3xl p-8 relative overflow-hidden">
                        <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-6">Live Card Preview</label>

                        {generatedCard ? (
                            <div className="space-y-6">
                                <div className="bg-white rounded-2xl p-8 text-center shadow-2xl border border-gray-200">
                                    <div className="w-12 h-1 bg-gray-100 mx-auto mb-8 rounded-full" />
                                    <h3 className="text-3xl font-black text-gray-900 mb-6 font-serif">
                                        {generatedCard.title}
                                    </h3>
                                    <p className="text-gray-600 text-lg leading-relaxed mb-8 italic font-serif">
                                        {generatedCard.message}
                                    </p>
                                    <div className="text-2xl font-black text-blue-600 tracking-tight font-serif">
                                        — {generatedCard.signature}
                                    </div>
                                </div>

                                <button
                                    onClick={handleDownload}
                                    className="w-full py-4 bg-green-600 text-white font-bold rounded-xl hover:bg-green-700 transition-all flex items-center justify-center gap-2 shadow-lg"
                                >
                                    <Download className="h-5 w-5" />
                                    Download Print-Ready PDF
                                </button>

                                <div className="flex items-center gap-2 justify-center text-[10px] text-gray-500 font-bold uppercase tracking-widest">
                                    <Check className="h-3 w-3 text-green-500" />
                                    Optimized for 5x7 Cardstock
                                </div>
                            </div>
                        ) : (
                            <div className="h-[450px] flex items-center justify-center text-gray-700 border-2 border-dashed border-gray-800 rounded-3xl">
                                <div className="text-center">
                                    <Gift className="h-16 w-16 mx-auto mb-4 opacity-50" />
                                    <p className="text-sm font-bold uppercase tracking-widest">Draft Ready</p>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
}
