'use client';

import { useState, useEffect } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import {
    Calendar,
    Zap,
    DollarSign,
    Maximize2,
    Plus,
    RefreshCw,
    Sparkles,
    TrendingUp,
    AlertCircle,
    ChevronRight,
    CheckCircle2
} from 'lucide-react';

interface Recommendation {
    id: string;
    subject: string;
    wvs: number;
    velocity: number;
    medianPrice: number;
    targetPrice: number;
    recommendedSizes: string[];
    confidence: number;
    date: string;
}

export default function ArtPlanner() {
    const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [isAdding, setIsAdding] = useState<string | null>(null);
    const [addedIds, setAddedIds] = useState<Set<string>>(new Set());

    useEffect(() => {
        loadRecommendations();
    }, []);

    const loadRecommendations = async () => {
        try {
            const res = await fetch('/api/art-planner');
            const data = await res.json();
            if (data.success) {
                setRecommendations(data.recommendations);
            }
        } catch (err) {
            console.error('Error loading recommendations:', err);
        } finally {
            setIsLoading(false);
        }
    };

    const addToQueue = async (rec: Recommendation) => {
        setIsAdding(rec.id);
        try {
            const res = await fetch('/api/paint-queue', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    action: 'add',
                    item: {
                        style: rec.subject,
                        size: rec.recommendedSizes[0],
                        medium: 'Acrylic',
                        targetPrice: rec.targetPrice,
                        notes: `Generated by Art Planner for ${rec.date}. WVS: ${rec.wvs}`
                    }
                }),
            });
            if (res.ok) {
                setAddedIds(prev => new Set(prev).add(rec.id));
            }
        } catch (err) {
            console.error('Error adding to queue:', err);
        } finally {
            setIsAdding(null);
        }
    };

    const getWvsColor = (score: number) => {
        if (score >= 4) return 'text-orange-500';
        if (score >= 2) return 'text-yellow-500';
        return 'text-blue-500';
    };

    const getWvsLabel = (score: number) => {
        if (score >= 4) return 'Hot Pulse';
        if (score >= 2) return 'Solid Demand';
        return 'Steady Velocity';
    };

    return (
        <DashboardLayout>
            <div className="space-y-8">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div>
                        <h1 className="text-3xl font-bold text-white mb-2">Art Planner</h1>
                        <p className="text-gray-400">Weekly recommendations powered by ArtScaler Intelligence</p>
                    </div>
                    <button
                        onClick={() => {
                            setIsLoading(true);
                            loadRecommendations();
                        }}
                        className="flex items-center gap-2 px-4 py-2 bg-gray-800 hover:bg-gray-700 text-white rounded-lg transition-all border border-gray-700"
                    >
                        <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
                        Refresh Plan
                    </button>
                </div>

                {isLoading ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {[1, 2, 3].map(i => (
                            <div key={i} className="bg-gray-900/50 border border-gray-800 rounded-2xl h-80 animate-pulse" />
                        ))}
                    </div>
                ) : recommendations.length === 0 ? (
                    <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-12 text-center">
                        <div className="w-16 h-16 bg-blue-500/10 rounded-full flex items-center justify-center mx-auto mb-6">
                            <Calendar className="h-8 w-8 text-blue-500" />
                        </div>
                        <h2 className="text-2xl font-bold text-white mb-2">Analyzing Marketplace...</h2>
                        <p className="text-gray-400 max-w-md mx-auto mb-8">
                            We're still processing the latest eBay data for your niche. Your weekly plan will appear here shortly.
                        </p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {recommendations.map((rec) => (
                            <div
                                key={rec.id}
                                className="group bg-gray-900/40 backdrop-blur-sm border border-gray-800 rounded-2xl overflow-hidden hover:border-blue-500/50 transition-all duration-300 flex flex-col"
                            >
                                {/* Header */}
                                <div className="p-6 border-b border-gray-800/50 bg-gradient-to-br from-gray-900 to-gray-900/40">
                                    <div className="flex items-center justify-between mb-4">
                                        <div className={`flex items-center gap-1.5 px-3 py-1 rounded-full bg-gray-800 border border-gray-700 text-xs font-bold uppercase tracking-wider ${getWvsColor(rec.wvs)}`}>
                                            <Zap className="h-3 w-3 fill-current" />
                                            {getWvsLabel(rec.wvs)}
                                        </div>
                                        <div className="flex items-center gap-1 text-xs text-gray-500">
                                            <Sparkles className="h-3 w-3 text-purple-400" />
                                            {Math.round(rec.confidence * 100)}% Match
                                        </div>
                                    </div>
                                    <h3 className="text-2xl font-bold text-white mb-1 group-hover:text-blue-400 transition-colors">
                                        {rec.subject}
                                    </h3>
                                    <p className="text-sm text-gray-400">Targeting {rec.recommendedSizes[0]} collectors</p>
                                </div>

                                {/* Stats */}
                                <div className="p-6 space-y-4 flex-1">
                                    <div className="grid grid-cols-2 gap-4">
                                        <div className="space-y-1">
                                            <span className="text-xs text-gray-500 uppercase font-semibold">Pulse Velocity</span>
                                            <div className="flex items-center gap-2">
                                                <div className="flex-1 h-1.5 bg-gray-800 rounded-full overflow-hidden">
                                                    <div
                                                        className="h-full bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.5)]"
                                                        style={{ width: `${Math.min(rec.wvs * 20, 100)}%` }}
                                                    />
                                                </div>
                                                <span className="text-sm font-bold text-white">{rec.wvs.toFixed(1)}</span>
                                            </div>
                                        </div>
                                        <div className="space-y-1">
                                            <span className="text-xs text-gray-500 uppercase font-semibold">Target Price</span>
                                            <div className="flex items-center gap-1 text-green-400 font-bold">
                                                <DollarSign className="h-4 w-4" />
                                                <span className="text-lg">${rec.targetPrice}</span>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="bg-gray-800/30 rounded-xl p-4 border border-gray-800">
                                        <div className="flex items-center gap-2 text-sm text-gray-300 mb-2">
                                            <Maximize2 className="h-4 w-4 text-purple-400" />
                                            <span className="font-semibold">Optimal Sizes:</span>
                                        </div>
                                        <div className="flex flex-wrap gap-2">
                                            {rec.recommendedSizes.map(size => (
                                                <span key={size} className="px-2 py-1 bg-gray-800 text-xs text-white rounded border border-gray-700">
                                                    {size}
                                                </span>
                                            ))}
                                        </div>
                                    </div>

                                    <div className="flex items-start gap-3 bg-blue-500/5 p-3 rounded-lg border border-blue-500/10">
                                        <AlertCircle className="h-5 w-5 text-blue-400 flex-shrink-0 mt-0.5" />
                                        <p className="text-xs text-blue-300/80 leading-relaxed">
                                            Market data shows high scarcity for {rec.subject} in {rec.recommendedSizes[0]}. Potential to exceed target price by 15%.
                                        </p>
                                    </div>
                                </div>

                                {/* Action */}
                                <div className="p-6 pt-0">
                                    <button
                                        onClick={() => addToQueue(rec)}
                                        disabled={isAdding === rec.id || addedIds.has(rec.id)}
                                        className={`w-full flex items-center justify-center gap-2 py-3 rounded-xl font-bold transition-all duration-300 ${addedIds.has(rec.id)
                                                ? 'bg-green-600/20 text-green-400 border border-green-500/30 cursor-default'
                                                : 'bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-600/20 hover:shadow-blue-500/30'
                                            }`}
                                    >
                                        {isAdding === rec.id ? (
                                            <RefreshCw className="h-5 w-5 animate-spin" />
                                        ) : addedIds.has(rec.id) ? (
                                            <>
                                                <CheckCircle2 className="h-5 w-5" />
                                                Added to Queue
                                            </>
                                        ) : (
                                            <>
                                                <Plus className="h-5 w-5" />
                                                Add to Paint Queue
                                            </>
                                        )}
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                )}

                {/* Legend or Guide */}
                <div className="bg-gray-900/30 border border-gray-800 rounded-2xl p-6 flex flex-col md:flex-row items-center gap-8">
                    <div className="flex-1">
                        <h4 className="text-lg font-bold text-white mb-2 flex items-center gap-2">
                            <TrendingUp className="h-5 w-5 text-blue-500" />
                            How to use your Weekly Plan
                        </h4>
                        <p className="text-sm text-gray-400 leading-relaxed">
                            Recommendations are ranked by <strong>Pulse Velocity (WVS)</strong>. Focus on "Hot Pulse" items for maximum turnover, and "Steady Velocity" items for consistent baseline revenue.
                        </p>
                    </div>
                    <div className="flex items-center gap-4 text-sm font-semibold text-gray-400">
                        <div className="flex items-center gap-1.5">
                            <div className="w-3 h-3 rounded-full bg-orange-500" />
                            High Demand
                        </div>
                        <div className="flex items-center gap-1.5">
                            <div className="w-3 h-3 rounded-full bg-yellow-500" />
                            Good Demand
                        </div>
                        <div className="flex items-center gap-1.5">
                            <div className="w-3 h-3 rounded-full bg-blue-500" />
                            Moderate
                        </div>
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
}
