'use client';

import { useState, useEffect } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import {
    Calendar,
    Zap,
    DollarSign,
    Maximize2,
    Plus,
    RefreshCw,
    Sparkles,
    TrendingUp,
    AlertCircle,
    CheckCircle2
} from 'lucide-react';
import { DEMO_PLANNER_RECS } from '@/lib/demo-data';

interface Recommendation {
    id: string;
    subject: string;
    wvs: number;
    velocity: number;
    medianPrice: number;
    targetPrice: number;
    recommendedSizes: string[];
    confidence: number;
    date: string;
}

export default function ArtPlanner() {
    const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [isAdding, setIsAdding] = useState<string | null>(null);
    const [addedIds, setAddedIds] = useState<Set<string>>(new Set());

    useEffect(() => {
        loadRecommendations();
    }, []);

    const loadRecommendations = async () => {
        setIsLoading(true);
        try {
            const res = await fetch('/api/art-planner');
            const data = await res.json();
            if (data.success && data.recommendations.length > 0) {
                setRecommendations(data.recommendations);
            } else {
                let preferredStyles: string[] = [];
                if (typeof window !== 'undefined') {
                    const saved = localStorage.getItem('artscaler_pref_styles');
                    if (saved) preferredStyles = JSON.parse(saved);
                }

                const mapped = DEMO_PLANNER_RECS.map((r, i) => ({
                    id: `demo-${i}`,
                    subject: r.subject,
                    wvs: r.score,
                    velocity: r.score,
                    medianPrice: 150,
                    targetPrice: 185,
                    recommendedSizes: ['16x20'],
                    confidence: 0.92,
                    date: new Date().toLocaleDateString()
                }));

                const sorted = [...mapped].sort((a, b) => {
                    const aMatch = preferredStyles.some(s => a.subject.toLowerCase().includes(s.toLowerCase().replace('_', ' ')));
                    const bMatch = preferredStyles.some(s => b.subject.toLowerCase().includes(s.toLowerCase().replace('_', ' ')));
                    if (aMatch && !bMatch) return -1;
                    if (!aMatch && bMatch) return 1;
                    return 0;
                });

                setRecommendations(sorted as any);
            }
        } catch (err) {
        } finally {
            setIsLoading(false);
        }
    };

    const addToQueue = async (rec: Recommendation) => {
        setIsAdding(rec.id);
        try {
            const res = await fetch('/api/paint-queue', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    action: 'add',
                    item: {
                        style: rec.subject,
                        size: rec.recommendedSizes[0],
                        medium: 'Acrylic',
                        targetPrice: rec.targetPrice,
                        notes: `Generated by Art Planner for ${rec.date}. WVS: ${rec.wvs}`
                    }
                }),
            });
            if (res.ok) {
                setAddedIds(prev => new Set(prev).add(rec.id));
            }
        } catch (err) {
        } finally {
            setIsAdding(null);
        }
    };

    const getWvsColor = (score: number) => {
        if (score >= 7) return 'text-orange-500 bg-orange-500/10 border-orange-500/20';
        if (score >= 4) return 'text-yellow-500 bg-yellow-500/10 border-yellow-500/20';
        return 'text-blue-500 bg-blue-500/10 border-blue-500/20';
    };

    const getWvsLabel = (score: number) => {
        if (score >= 7) return 'Hot Pulse';
        if (score >= 4) return 'Solid Demand';
        return 'Steady Velocity';
    };

    return (
        <DashboardLayout>
            <div className="space-y-12">
                {/* V6 Title Row */}
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 py-6">
                    <div>
                        <div className="flex items-center gap-2 mb-4">
                            <span className="text-xs font-black text-blue-500 uppercase tracking-widest">Niche Intelligence</span>
                        </div>
                        <h1 className="text-4xl md:text-6xl font-black text-white italic tracking-tighter uppercase leading-[0.9]">
                            Art Strategy <br />
                            <span className="text-gray-700">Builder</span>
                        </h1>
                    </div>
                    <div className="flex items-center gap-4">
                        <button
                            onClick={() => {
                                setIsLoading(true);
                                loadRecommendations();
                            }}
                            className="flex items-center gap-2 px-6 py-4 bg-gray-900 hover:bg-gray-800 text-gray-400 hover:text-white rounded-2xl transition-all border border-white/5 font-black uppercase tracking-widest text-xs"
                        >
                            <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
                            Refresh Strategy
                        </button>
                    </div>
                </div>

                {isLoading ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {[1, 2, 3, 4, 5, 6].map(i => (
                            <div key={i} className="bg-gray-900/50 border border-white/5 rounded-[32px] h-[400px] animate-pulse" />
                        ))}
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {recommendations.map((rec) => (
                            <div
                                key={rec.id}
                                className="group bg-gray-900 border border-white/5 rounded-[40px] p-8 flex flex-col transition-all hover:-translate-y-2 hover:border-blue-500/30 overflow-hidden relative"
                            >
                                {/* Decorative Gradient */}
                                <div className="absolute top-0 right-0 w-32 h-32 bg-blue-600/5 blur-3xl rounded-full group-hover:bg-blue-600/10 transition-colors"></div>

                                <div className="flex items-center justify-between mb-8 relative z-10">
                                    <div className={`flex items-center gap-1.5 px-4 py-1.5 rounded-full border text-[10px] font-black uppercase tracking-widest ${getWvsColor(rec.wvs)}`}>
                                        <Zap className="h-3 w-3 fill-current" />
                                        {getWvsLabel(rec.wvs)}
                                    </div>
                                    <div className="text-[10px] font-black text-gray-500 uppercase tracking-widest">
                                        WVS {rec.wvs.toFixed(1)}
                                    </div>
                                </div>

                                <div className="mb-6 relative z-10">
                                    <h3 className="text-2xl font-black text-white uppercase italic tracking-tighter mb-1 group-hover:text-blue-500 transition-colors">
                                        {rec.subject}
                                    </h3>
                                    <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Confidence: {Math.round(rec.confidence * 100)}%</p>
                                </div>

                                <div className="grid grid-cols-2 gap-4 mb-8 relative z-10">
                                    <div className="p-4 bg-white/5 rounded-2xl border border-white/5">
                                        <p className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-1">Target Price</p>
                                        <div className="flex items-center gap-1 text-green-500 font-black text-xl italic">
                                            <span className="text-xs non-italic">$</span>
                                            {rec.targetPrice}
                                        </div>
                                    </div>
                                    <div className="p-4 bg-white/5 rounded-2xl border border-white/5">
                                        <p className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-1">Optimal Size</p>
                                        <div className="text-sm font-black text-white uppercase mt-1.5">{rec.recommendedSizes[0]}</div>
                                    </div>
                                </div>

                                <div className="mb-8 p-4 bg-blue-600/5 border border-blue-600/10 rounded-2xl relative z-10">
                                    <div className="flex items-center gap-2 mb-2">
                                        <AlertCircle className="h-3 w-3 text-blue-500" />
                                        <p className="text-[10px] font-black text-blue-500 uppercase tracking-widest">Market Recommendation</p>
                                    </div>
                                    <p className="text-xs font-bold text-gray-300 leading-relaxed uppercase">
                                        Create 2-3 pieces with <span className="text-white">vibrant textures</span> to minimize competition and maximize conversion.
                                    </p>
                                </div>

                                <button
                                    onClick={() => addToQueue(rec)}
                                    disabled={isAdding === rec.id || addedIds.has(rec.id)}
                                    className={`w-full py-4 rounded-2xl font-black uppercase text-xs tracking-[0.2em] transition-all relative z-10 mt-auto ${addedIds.has(rec.id)
                                        ? 'bg-green-600/10 text-green-500 border border-green-500/20'
                                        : 'bg-blue-600 hover:bg-blue-500 text-white shadow-xl shadow-blue-600/20'
                                        }`}
                                >
                                    {isAdding === rec.id ? (
                                        <RefreshCw className="h-4 w-4 animate-spin mx-auto" />
                                    ) : addedIds.has(rec.id) ? (
                                        <div className="flex items-center justify-center gap-2">
                                            <CheckCircle2 className="h-4 w-4" />
                                            <span>In Production</span>
                                        </div>
                                    ) : (
                                        <div className="flex items-center justify-center gap-2">
                                            <Plus className="h-4 w-4" />
                                            <span>Add to Queue</span>
                                        </div>
                                    )}
                                </button>
                            </div>
                        ))}
                    </div>
                )}

                {/* Legend Guide */}
                <div className="bg-gray-900 border border-white/5 rounded-[40px] p-10 flex flex-col md:flex-row items-center gap-10">
                    <div className="w-16 h-16 bg-blue-600/10 rounded-2xl flex items-center justify-center shrink-0">
                        <TrendingUp className="h-8 w-8 text-blue-500" />
                    </div>
                    <div>
                        <h4 className="text-xl font-black text-white uppercase italic tracking-tighter mb-2">Intelligence Guide</h4>
                        <p className="text-xs font-bold text-gray-500 uppercase leading-relaxed tracking-wider">
                            Recommendations are calibrated using <span className="text-white">Global Market Pulse</span> data. "Hot Pulse" items represent the highest search-to-sale ratio in the current 24-hour cycle. Focus your production on these topics to maximize inventory turnover.
                        </p>
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
}
