'use client';

import { useState } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { FileText, Download, Palette, Type, Image as ImageIcon, QrCode, Save, Sparkles } from 'lucide-react';
import * as QRCode from 'qrcode';
import { jsPDF } from 'jspdf';

export default function COAGenerator() {
    const [formData, setFormData] = useState({
        artworkTitle: '',
        artistName: '',
        medium: '',
        dimensions: '',
        creationDate: '',
        editionType: 'original',
        editionNumber: '',
        totalEditions: '',
        description: ''
    });

    const [template, setTemplate] = useState('classic');
    const [qrCodeUrl, setQrCodeUrl] = useState('');
    const [coaNumber, setCoaNumber] = useState('');

    const templates = [
        { id: 'classic', name: 'Classic Elegance', preview: 'Traditional serif fonts with gold accents' },
        { id: 'modern', name: 'Modern Minimal', preview: 'Clean sans-serif with bold typography' },
        { id: 'artistic', name: 'Artistic Flair', preview: 'Creative layout with artistic elements' },
        { id: 'luxury', name: 'Luxury Premium', preview: 'Sophisticated design with premium feel' }
    ];

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const generateCOANumber = () => {
        const year = new Date().getFullYear();
        const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
        const artistCode = formData.artistName.substring(0, 3).toUpperCase() || 'ART';
        return `${artistCode}-${year}-${random}`;
    };

    const generateQRCode = async (coaNum: string) => {
        try {
            const verificationUrl = `https://ebayartpulse.com/verify/${coaNum}`;
            const qrDataUrl = await QRCode.toDataURL(verificationUrl, {
                width: 200,
                margin: 2,
                color: {
                    dark: '#000000',
                    light: '#FFFFFF'
                }
            });
            setQrCodeUrl(qrDataUrl);
        } catch (error) {
            console.error('QR Code generation error:', error);
        }
    };

    const handleGenerate = async () => {
        const newCoaNumber = generateCOANumber();
        setCoaNumber(newCoaNumber);
        await generateQRCode(newCoaNumber);
    };

    const handleDownloadPDF = () => {
        const doc = new jsPDF();

        // Classic Template Layout
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.text('CERTIFICATE OF AUTHENTICITY', 105, 30, { align: 'center' });

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`COA Number: ${coaNumber}`, 105, 40, { align: 'center' });

        // Artwork Details
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Artwork Details', 20, 60);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.text(`Title: ${formData.artworkTitle}`, 20, 70);
        doc.text(`Artist: ${formData.artistName}`, 20, 78);
        doc.text(`Medium: ${formData.medium}`, 20, 86);
        doc.text(`Dimensions: ${formData.dimensions}`, 20, 94);
        doc.text(`Creation Date: ${formData.creationDate}`, 20, 102);

        if (formData.editionType !== 'original') {
            doc.text(`Edition: ${formData.editionNumber} of ${formData.totalEditions}`, 20, 110);
        } else {
            doc.text('Edition: Original (1 of 1)', 20, 110);
        }

        // Description
        if (formData.description) {
            doc.setFont('helvetica', 'bold');
            doc.text('Description', 20, 125);
            doc.setFont('helvetica', 'normal');
            const splitDescription = doc.splitTextToSize(formData.description, 170);
            doc.text(splitDescription, 20, 133);
        }

        // QR Code
        if (qrCodeUrl) {
            doc.addImage(qrCodeUrl, 'PNG', 160, 220, 40, 40);
            doc.setFontSize(8);
            doc.text('Scan to verify', 180, 265, { align: 'center' });
        }

        // Footer
        doc.setFontSize(8);
        doc.text('This certificate confirms the authenticity of the artwork described above.', 105, 280, { align: 'center' });
        doc.text(`Generated by ArtScaler on ${new Date().toLocaleDateString()}`, 105, 285, { align: 'center' });

        doc.save(`COA-${coaNumber}.pdf`);
    };

    return (
        <DashboardLayout>
            <div className="max-w-6xl mx-auto space-y-8">
                {/* Header */}
                <div>
                    <h1 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
                        <FileText className="h-8 w-8 text-blue-500" />
                        Certificate of Authenticity Generator
                    </h1>
                    <p className="text-gray-400">Create professional COAs for your artwork with auto-numbering and QR verification</p>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Form Section */}
                    <div className="space-y-6">
                        {/* Template Selection */}
                        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6">
                            <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                                <Palette className="h-5 w-5 text-purple-500" />
                                Choose Template
                            </h3>
                            <div className="grid grid-cols-2 gap-3">
                                {templates.map(t => (
                                    <button
                                        key={t.id}
                                        onClick={() => setTemplate(t.id)}
                                        className={`p-4 rounded-xl border-2 transition-all text-left ${template === t.id
                                            ? 'border-blue-500 bg-blue-900/20'
                                            : 'border-gray-700 hover:border-gray-600'
                                            }`}
                                    >
                                        <p className="font-bold text-white text-sm mb-1">{t.name}</p>
                                        <p className="text-xs text-gray-400">{t.preview}</p>
                                    </button>
                                ))}
                            </div>
                        </div>

                        {/* Artwork Details */}
                        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-4">
                            <h3 className="text-lg font-bold text-white mb-4">Artwork Details</h3>

                            <div>
                                <label htmlFor="artworkTitle" className="block text-sm font-medium text-gray-400 mb-2">Artwork Title *</label>
                                <input
                                    id="artworkTitle"
                                    type="text"
                                    name="artworkTitle"
                                    value={formData.artworkTitle}
                                    onChange={handleInputChange}
                                    placeholder="e.g., Ocean Waves at Sunset"
                                    className="w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                                />
                            </div>

                            <div>
                                <label htmlFor="artistName" className="block text-sm font-medium text-gray-400 mb-2">Artist Name *</label>
                                <input
                                    id="artistName"
                                    type="text"
                                    name="artistName"
                                    value={formData.artistName}
                                    onChange={handleInputChange}
                                    placeholder="Your full name"
                                    className="w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label htmlFor="medium" className="block text-sm font-medium text-gray-400 mb-2">Medium</label>
                                    <input
                                        id="medium"
                                        type="text"
                                        name="medium"
                                        value={formData.medium}
                                        onChange={handleInputChange}
                                        placeholder="e.g., Oil on Canvas"
                                        className="w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                                    />
                                </div>
                                <div>
                                    <label htmlFor="dimensions" className="block text-sm font-medium text-gray-400 mb-2">Dimensions</label>
                                    <input
                                        id="dimensions"
                                        type="text"
                                        name="dimensions"
                                        value={formData.dimensions}
                                        onChange={handleInputChange}
                                        placeholder='e.g., 24" x 36"'
                                        className="w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                                    />
                                </div>
                            </div>

                            <div>
                                <label htmlFor="creationDate" className="block text-sm font-medium text-gray-400 mb-2">Creation Date</label>
                                <input
                                    id="creationDate"
                                    type="date"
                                    name="creationDate"
                                    value={formData.creationDate}
                                    onChange={handleInputChange}
                                    className="w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                                />
                            </div>

                            <div>
                                <label htmlFor="editionType" className="block text-sm font-medium text-gray-400 mb-2">Edition Type</label>
                                <select
                                    id="editionType"
                                    name="editionType"
                                    value={formData.editionType}
                                    onChange={handleInputChange}
                                    className="w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                                >
                                    <option value="original">Original (1 of 1)</option>
                                    <option value="limited">Limited Edition</option>
                                    <option value="open">Open Edition</option>
                                    <option value="print">Print</option>
                                </select>
                            </div>

                            {formData.editionType !== 'original' && (
                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <label htmlFor="editionNumber" className="block text-sm font-medium text-gray-400 mb-2">Edition #</label>
                                        <input
                                            id="editionNumber"
                                            type="number"
                                            name="editionNumber"
                                            value={formData.editionNumber}
                                            onChange={handleInputChange}
                                            placeholder="1"
                                            className="w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                                        />
                                    </div>
                                    <div>
                                        <label htmlFor="totalEditions" className="block text-sm font-medium text-gray-400 mb-2">Total Editions</label>
                                        <input
                                            id="totalEditions"
                                            type="number"
                                            name="totalEditions"
                                            value={formData.totalEditions}
                                            onChange={handleInputChange}
                                            placeholder="100"
                                            className="w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                                        />
                                    </div>
                                </div>
                            )}

                            <div>
                                <label htmlFor="description" className="block text-sm font-medium text-gray-400 mb-2">Description (Optional)</label>
                                <textarea
                                    id="description"
                                    name="description"
                                    value={formData.description}
                                    onChange={handleInputChange}
                                    rows={3}
                                    placeholder="Brief description of the artwork..."
                                    className="w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                                />
                            </div>
                        </div>

                        {/* Actions */}
                        <div className="flex gap-3">
                            <button
                                onClick={handleGenerate}
                                className="flex-1 flex items-center justify-center gap-2 px-6 py-4 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 text-white rounded-xl font-bold transition-all shadow-lg"
                            >
                                <Sparkles className="h-5 w-5" />
                                Generate COA
                            </button>
                        </div>
                    </div>

                    {/* Preview Section */}
                    <div className="space-y-6">
                        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-8 min-h-[600px]">
                            <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
                                <ImageIcon className="h-5 w-5 text-green-500" />
                                Preview
                            </h3>

                            {coaNumber ? (
                                <div className="bg-white p-8 rounded-lg text-black">
                                    <div className="text-center mb-8">
                                        <h2 className="text-2xl font-bold mb-2">CERTIFICATE OF AUTHENTICITY</h2>
                                        <p className="text-sm text-gray-600">COA Number: {coaNumber}</p>
                                    </div>

                                    <div className="space-y-3 mb-6">
                                        <div className="border-b border-gray-300 pb-2">
                                            <p className="text-xs text-gray-600">Title</p>
                                            <p className="font-semibold">{formData.artworkTitle || 'Untitled'}</p>
                                        </div>
                                        <div className="border-b border-gray-300 pb-2">
                                            <p className="text-xs text-gray-600">Artist</p>
                                            <p className="font-semibold">{formData.artistName || 'Artist Name'}</p>
                                        </div>
                                        <div className="grid grid-cols-2 gap-4">
                                            <div className="border-b border-gray-300 pb-2">
                                                <p className="text-xs text-gray-600">Medium</p>
                                                <p className="font-semibold text-sm">{formData.medium || 'N/A'}</p>
                                            </div>
                                            <div className="border-b border-gray-300 pb-2">
                                                <p className="text-xs text-gray-600">Dimensions</p>
                                                <p className="font-semibold text-sm">{formData.dimensions || 'N/A'}</p>
                                            </div>
                                        </div>
                                        <div className="border-b border-gray-300 pb-2">
                                            <p className="text-xs text-gray-600">Edition</p>
                                            <p className="font-semibold">
                                                {formData.editionType === 'original'
                                                    ? 'Original (1 of 1)'
                                                    : `${formData.editionNumber || '?'} of ${formData.totalEditions || '?'}`
                                                }
                                            </p>
                                        </div>
                                    </div>

                                    {qrCodeUrl && (
                                        <div className="flex justify-center mb-4">
                                            <div className="text-center">
                                                <img src={qrCodeUrl} alt="QR Code" className="w-32 h-32 mx-auto" />
                                                <p className="text-xs text-gray-600 mt-2">Scan to verify authenticity</p>
                                            </div>
                                        </div>
                                    )}

                                    <div className="text-center text-xs text-gray-500 mt-6 pt-4 border-t border-gray-300">
                                        <p>This certificate confirms the authenticity of the artwork described above.</p>
                                        <p className="mt-1">Generated by ArtScaler • {new Date().toLocaleDateString()}</p>
                                    </div>
                                </div>
                            ) : (
                                <div className="flex items-center justify-center h-full">
                                    <div className="text-center text-gray-500">
                                        <FileText className="h-16 w-16 mx-auto mb-4 opacity-50" />
                                        <p>Fill in the details and click "Generate COA" to see preview</p>
                                    </div>
                                </div>
                            )}
                        </div>

                        {coaNumber && (
                            <button
                                onClick={handleDownloadPDF}
                                className="w-full flex items-center justify-center gap-2 px-6 py-4 bg-green-600 hover:bg-green-500 text-white rounded-xl font-bold transition-all"
                            >
                                <Download className="h-5 w-5" />
                                Download PDF
                            </button>
                        )}
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
}
